In [1]:
import torch


In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x, x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True) None


In [3]:
y = x + 2
print(y, y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x7fc6d809e550>


In [4]:
x.is_leaf, y.is_leaf

(True, False)

In [5]:
z = y*y*3
out = z.mean()
z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [6]:
a = torch.randn(2,2)
a = (a*3) / (a-1)
a.requires_grad

False

In [7]:
a.requires_grad_(True)
a.requires_grad

True

In [8]:
b = (a*a).sum()
b.grad_fn

In [9]:
out.backward() 
# out.backward(torch.tensor(1.))

In [10]:
# d(out)/dx
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


$$o=\frac{1}{4}\sum_{i=1}^{4}z_i=\frac{1}{4}\sum_{i=1}^{4}3(x_i+2)^2$$
$$\frac{\partial o}{\partial x_i}|_{x_i=1} = \frac{9}{2} = 4.5$$



In [11]:
# # 再来反向传播一次，注意grad是累加的
out2 = x.sum()
out2.backward()
x.grad

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])

In [13]:
out3 = x.sum()
x.grad.data.zero_()
out3.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [15]:
x = torch.tensor([1.0,2.0,3.0,4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
z

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)

In [16]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]])
z.backward(v)
x.grad

tensor([2.0000, 0.2000, 0.0200, 0.0020])

In [18]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x**2
with torch.no_grad():
    y2 = x**3

y3 = y1 + y2
x.requires_grad, y1.requires_grad, y2.requires_grad, y3.requires_grad

(True, True, False, True)

In [19]:
y3.backward()
x.grad

tensor(2.)

In [20]:
x = torch.ones(1, requires_grad=True)
x.data, x.data.requires_grad

(tensor([1.]), False)

In [22]:
y = 2*x
x.data *= 100
y.backward()
x, x.grad

(tensor([100.], requires_grad=True), tensor([2.]))